# Generated by Django 6.0.6 on 2026-06-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('degree_name', models.CharField(max_length=200)),
                ('latin_honor', models.CharField(blank=True, choices=[('', 'None'), ('cum_laude', 'Cum Laude'), ('magna_cum_laude', 'Magna Cum Laude'), ('summa_cum_laude', 'Summa Cum Laude')], default='', max_length=30)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='scholars/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='scholars/thumbs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
