# Generated by Django 6.0.6 on 2026-06-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_scholar_delete_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='school',
            field=models.CharField(default='', max_length=200),
        ),
    ]
