# Generated by Django 6.0.6 on 2026-06-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_scholar_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='region',
            field=models.CharField(choices=[('luzon', 'Luzon'), ('visayas', 'Visayas'), ('mindanao', 'Mindanao')], default='mindanao', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='school',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('head_officer', 'Head Officer')], max_length=20)),
                ('region', models.CharField(blank=True, choices=[('luzon', 'Luzon'), ('visayas', 'Visayas'), ('mindanao', 'Mindanao')], default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
